main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

details:
  method: 'get'
  path: details/{id}
  controller: App\Controller\HomeController
  action: details

favorite:
  method: 'get'
  path: favorite/{id}/{fav}
  controller: App\Controller\HomeController
  action: favorite

